database_settings:
  name: "bot_subscriptions.db"

logger_settings:
  name: "telegram_crypto_bot"

bot_settings:
  interval: 300
  default_startup_message: "Crypto bot is active!\nUse /subscribe <coin-name> <cost> <'above' | 'below'>."
  max_message_length: 4096
  max_run_tries: 5